# Generated by Django 6.0.3 on 2026-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='achados/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item Achado',
                'verbose_name_plural': 'Itens Achados',
                'db_table': 'itens_achados',
                'ordering': ['-criado_em'],
                'managed': False,
            },
        ),
    ]
