# Generated by Django 6.0.3 on 2026-05-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('TII', 'TII'), ('ADM', 'ADM'), ('ADS', 'ADS'), ('TPG', 'TPG')], max_length=10)),
                ('disciplina', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provas',
                'managed': False,
            },
        ),
    ]
