# Generated by Django 6.0.3 on 2026-05-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prova',
            options={'managed': False, 'ordering': ['data'], 'verbose_name': 'Prova', 'verbose_name_plural': 'Provas'},
        ),
    ]
